SPP-9996 Concourse Pipeline False Pass Fix
ONSdigital/sml-catalogue pull request #194
Opened 2023-09-22 08:18 UTC by sanjeevz3009

# Description

Please include a summary of the changes and features. Please also include relevant motivation and context. List any dependencies that are required for this change.

If you have not checked any of the lists below explain why here.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Technical Enhancements

# Checklist:

If any of these are not completed, please explain why in the notes.

## **Definition of Done**
**Code and merges**

- [ ] Code to be commented on where applicable 
- [ ] Documentation updated where required 
- [ ] Have considered non-functional requirements such as Security, Performance, Scalability, and Fault Tolerance
- [ ] I have linted the code

**Testing**

- [ ] All levels of acceptance test are passing (automated, integration, manual, accessibility, etc.)
- [ ] I have run the behave command to check the selenium behaviour tests pass locally
- [ ] Acceptance criteria met

**Other Checks**
- [ ] I have performed a self-review of my own code
- [ ] I have checked for spelling errors
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] My changes don't break anything unexpected
- [ ] I have checked and updated the security.txt file where required
- [ ] Up to date with the main branch

2023-09-22 08:32 UTC, sanjeevz3009 commented on ci/tasks/testing/run_bdd_tests.sh
> +set -e
Will take a look and make the changes. Thanks Jason ☺️

2023-09-22 08:54 UTC, ons-spp-machine-user commented
DEPLOY_URL=https://d1kjsi1gfnps2t.cloudfront.net/
cloudfront_id=E2DX0ZZXZHZ9N8

2023-09-22 09:03 UTC, sanjeevz3009 commented on ci/tasks/testing/run_bdd_tests.sh
> +set -e
My teams if bugging out on the Mac for some reason. I made the changes you asked and it's giving this entirely new error. Slack still works for me so you can send your messages there =)

2023-09-22 09:03 UTC, sanjeevz3009 commented on ci/tasks/testing/run_bdd_tests.sh
> +set -e
My teams if bugging out on the Mac for some reason. I made the changes you asked and it's giving this entirely new error. Slack still works for me so you can send your messages there =)

2023-09-22 10:03 UTC, ons-spp-machine-user commented
DEPLOY_URL=https://d1kjsi1gfnps2t.cloudfront.net/
cloudfront_id=E2DX0ZZXZHZ9N8

2023-09-22 10:36 UTC, ons-spp-machine-user commented
DEPLOY_URL=https://d1kjsi1gfnps2t.cloudfront.net/
cloudfront_id=E2DX0ZZXZHZ9N8

2023-09-25 14:51 UTC, ons-spp-machine-user commented
DEPLOY_URL=https://d1kjsi1gfnps2t.cloudfront.net/
cloudfront_id=E2DX0ZZXZHZ9N8

2023-09-25 15:17 UTC, sanjeevz3009 commented on ci/tasks/testing/run_bdd_tests.sh
> +set -e
Hello Jason, I think it all works now! I broke one of the BDD tests and the GitHub check for concourse failed successfully YAYYY!! If all is good, you can approve it and I'll fix the BDD test, squash and merge it.

2023-09-26 08:35 UTC, JasonBellONS requested changes
Two small requests but otherwise looks good, once those are done and the bdd test is fixed again i'll approve

2023-09-26 08:35 UTC, JasonBellONS commented on ci/tasks/testing/run_bdd_tests.sh
> +set -euo
should be -euo pipefail

2023-09-26 08:35 UTC, JasonBellONS commented on ci/live-pipeline.yml
> +        status: failure
can these two changes also be made to the chunk on code starting on line 316 please

2023-09-26 13:59 UTC, sanjeevz3009 commented on ci/tasks/testing/run_bdd_tests.sh
> +set -euo
Done!

2023-09-26 14:21 UTC, JasonBellONS requested changes
looks good, will approve once the bdd test is reverted and pipeline passes again

2023-09-26 15:20 UTC, ons-spp-machine-user commented
DEPLOY_URL=https://d1kjsi1gfnps2t.cloudfront.net/
cloudfront_id=E2DX0ZZXZHZ9N8

2023-09-27 07:50 UTC, JasonBellONS approved these changes
happy to approve

2023-09-27 15:24 UTC, merged