SPP-9546-amend-IDS-link-description
ONSdigital/sml-catalogue pull request #206
Opened 2023-10-03 15:37 UTC by joepercival

# Description

Links have been presented on the page using URL’s which do not describe the purpose of the links without the additional surrounding context on the page. This PR will amend the descriptions of these links in order to make them more accessible to users navigating out of the context of the page.

Code has not been commented and documentation has not been provided because it is not necessary for this PR.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Technical Enhancements

# Checklist:

If any of these are not completed, please explain why in the notes.

## **Definition of Done**
**Code and merges**

- [ ] Code to be commented on where applicable 
- [ ] Documentation updated where required 
- [x] Have considered non-functional requirements such as Security, Performance, Scalability, and Fault Tolerance
- [x] I have linted the code

**Testing**

- [x] All levels of acceptance test are passing (automated, integration, manual, accessibility, etc.)
- [x] I have run the behave command to check the selenium behaviour tests pass locally
- [x] Acceptance criteria met

**Other Checks**
- [x] I have performed a self-review of my own code
- [x] I have checked for spelling errors
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [x] My changes don't break anything unexpected
- [x] I have checked and updated the security.txt file where required
- [x] Up to date with the main branch

2023-10-03 15:42 UTC, ons-spp-machine-user commented
DEPLOY_URL=https://drnd6r2akxm01.cloudfront.net/
cloudfront_id=E1VWPRF2OIE3K8

2023-10-11 10:18 UTC, ons-spp-machine-user commented
DEPLOY_URL=https://drnd6r2akxm01.cloudfront.net/
cloudfront_id=E1VWPRF2OIE3K8

2023-10-18 10:35 UTC, jhmjam requested changes

2023-10-18 10:35 UTC, jhmjam commented on content/help_centre/run-a-method.md
> +    - [SML Python-Small releases](https://github.com/ONSdigital/sml-python-small/releases)
May want to remove the dash here and add repository to the end of small :)

2023-10-18 15:09 UTC, jhmjam submitted a review, later dismissed

2023-10-19 08:44 UTC, ons-spp-machine-user commented
DEPLOY_URL=https://drnd6r2akxm01.cloudfront.net/
cloudfront_id=E1VWPRF2OIE3K8

2023-10-19 09:01 UTC, jhmjam approved these changes

2023-10-19 09:08 UTC, ons-spp-machine-user commented
DEPLOY_URL=https://drnd6r2akxm01.cloudfront.net/
cloudfront_id=E1VWPRF2OIE3K8

2023-10-19 09:14 UTC, merged