amending installed package list
ONSdigital/sml-catalogue pull request #389
Opened 2024-10-10 10:07 UTC by JasonBellONS

amending installed package list to correctly install cython for pandas installation as a subpackage

2024-10-10 10:16 UTC, ons-spp-machine-user commented
DEPLOY_URL=https://dc2kio1yw8kuv.cloudfront.net/
cloudfront_id=EKBNK1K1QJGP1

2024-10-10 10:22 UTC, ons-spp-machine-user commented
DEPLOY_URL=https://dc2kio1yw8kuv.cloudfront.net/
cloudfront_id=EKBNK1K1QJGP1

2024-10-10 10:24 UTC, ons-spp-machine-user commented
DEPLOY_URL=https://dc2kio1yw8kuv.cloudfront.net/
cloudfront_id=EKBNK1K1QJGP1

2024-10-10 10:42 UTC, ons-spp-machine-user commented
DEPLOY_URL=https://dc2kio1yw8kuv.cloudfront.net/
cloudfront_id=EKBNK1K1QJGP1

2024-10-10 11:06 UTC, ons-spp-machine-user commented
DEPLOY_URL=https://dc2kio1yw8kuv.cloudfront.net/
cloudfront_id=EKBNK1K1QJGP1

2024-10-10 11:51 UTC, ons-spp-machine-user commented
DEPLOY_URL=https://dc2kio1yw8kuv.cloudfront.net/
cloudfront_id=EKBNK1K1QJGP1

2024-10-10 12:00 UTC, ons-spp-machine-user commented
DEPLOY_URL=https://dc2kio1yw8kuv.cloudfront.net/
cloudfront_id=EKBNK1K1QJGP1

2024-10-10 12:10 UTC, ons-spp-machine-user commented
DEPLOY_URL=https://dc2kio1yw8kuv.cloudfront.net/
cloudfront_id=EKBNK1K1QJGP1

2024-10-10 12:33 UTC, ons-spp-machine-user commented
DEPLOY_URL=https://dc2kio1yw8kuv.cloudfront.net/
cloudfront_id=EKBNK1K1QJGP1

2024-10-10 12:47 UTC, ons-spp-machine-user commented
DEPLOY_URL=https://dc2kio1yw8kuv.cloudfront.net/
cloudfront_id=EKBNK1K1QJGP1

2024-10-10 13:18 UTC, ons-spp-machine-user commented
DEPLOY_URL=https://dc2kio1yw8kuv.cloudfront.net/
cloudfront_id=EKBNK1K1QJGP1

2024-10-10 15:08 UTC, ons-spp-machine-user commented
DEPLOY_URL=https://dc2kio1yw8kuv.cloudfront.net/
cloudfront_id=EKBNK1K1QJGP1

2024-10-10 15:11 UTC, gibbardsteve commented
It looks like CICD is bailing still...
![image](https://github.com/user-attachments/assets/69ddaca7-0be1-4f32-89d2-c3ac670c1b82)

2024-10-10 15:46 UTC, JasonBellONS commented
> It looks like CICD is bailing still... ![image](https://private-user-images.githubusercontent.com/88480716/375437984-69ddaca7-0be1-4f32-89d2-c3ac670c1b82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NzU0NTEsIm5iZiI6MTcyODU3NTE1MSwicGF0aCI6Ii84ODQ4MDcxNi8zNzU0Mzc5ODQtNjlkZGFjYTctMGJlMS00ZjMyLTg5ZDItYzNhYzY3MGMxYjgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDE1NDU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyNzIwZjcxYjQ1N2I2MGJkYTg5M2M0NjdjYjBmOGRmZWUxYTA2YjExMGEyYTI4NDYyNTc5NGQ5YTAxYWU1NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1SfrjJ81B0OhT3WqbJD9eKeidop1ZJIxC3df_8C-JrU)

seems to be due to python on the containers now suddenly being 3.13 of python (previously 3.12.7). If i cant get it working i may need to speak to shared services about getting a temporary version of the container created with 3.12.7 again

2024-10-11 09:03 UTC, ons-spp-machine-user commented
DEPLOY_URL=https://dc2kio1yw8kuv.cloudfront.net/
cloudfront_id=EKBNK1K1QJGP1

2024-10-11 09:09 UTC, ons-spp-machine-user commented
DEPLOY_URL=https://dc2kio1yw8kuv.cloudfront.net/
cloudfront_id=EKBNK1K1QJGP1

2024-10-11 09:14 UTC, ons-spp-machine-user commented
DEPLOY_URL=https://dc2kio1yw8kuv.cloudfront.net/
cloudfront_id=EKBNK1K1QJGP1

2024-10-11 09:20 UTC, ons-spp-machine-user commented
DEPLOY_URL=https://dc2kio1yw8kuv.cloudfront.net/
cloudfront_id=EKBNK1K1QJGP1

2024-10-11 09:22 UTC, JasonBellONS commented
Method and glossary amended to remove jsonnet package (note this breaks non contentful runs, a second branch will be created to implement regular .json files for these two pages)

2024-10-11 09:35 UTC, jhmjam requested changes

2024-10-11 09:35 UTC, jhmjam commented on sml_builder/method.py
> +    # methods_dir = "./content/methods/ready-to-use-methods"
delete these?

2024-10-11 09:35 UTC, jhmjam commented on sml_builder/method.py
> +# def appendRow(methods_dir, filter_methods=None):
and these?

2024-10-11 09:39 UTC, jhmjam approved these changes

2024-10-11 09:40 UTC, merged